### ISSUE TITLE
Hey man thanks for the release, but i think the ANN model file is missing?

### ISSUE THREAD

**Issue by boonpflug** [ChihChiangHuang/AlbionFishingBot#1]
As i said, the code crashes as it looks for a .pb file. did you forget to check it in maybe? Would love to try it out!

**Comment by ChihChiangHuang** [comment]
Hi, you can find the ANN model from the release. I just uploaded it.

However, I would suggest building your own model because all the data are acquired from my PC. The ANN may be overfitted to the configuration of my PC.

To build your own ANN, disable the enable_NN in the main script first. Run the main script for some time to get enough data. Run the ANN_build script to build your own ANN model. Then, enable the enable_NN in the main script.

**Comment by AIshouldbecry** [comment]
how to enable_NN from the code. i am a tensorflow noob
